### ISSUE TITLE
Setup Styleguide 

### ISSUE THREAD

**Issue by naufaldi** [naufaldi/nextjs-chakra-notion-blog#1]
Setup styleguide sesuai dengan Figma.
Link Figma [UI Kit Blog](https://www.figma.com/community/file/825069539366152961)

**Comment by Aqshola** [comment]
wip

**Comment by naufaldi** [comment]
setup styleguide tidak hanya font. tapi juga seperti color pallette, font size, font family. Lihat contoh di [theme chakra UI](https://github.com/naufaldi/future-bright/blob/master/styles/theme.js) @Aqshola

**Comment by Aqshola** [comment]
dari source desain, cuman provide font size, family, weight. untuk color pallete cuman black dan bisa pake default chakra ui, berarti nanti saya tinggal fix font family sama font weight?

**Comment by naufaldi** [comment]
betul sekali
