### ISSUE TITLE
Error Footer Height

### ISSUE THREAD

**Issue by naufaldi** [naufaldi/nextjs-chakra-notion-blog#11]
## Description: 
Ada masalah di bagian Height Footer. Mohon untuk diperbaiki.

## Screenshot
<img width="1440" alt="Screen Shot 2021-05-30 at 15 32 31" src="https://user-images.githubusercontent.com/13159420/120097699-41cc6b80-c15c-11eb-8b89-1033def1fe3f.png">

**Comment by Aqshola** [comment]
wip
