### ISSUE TITLE
Setup Layout

### ISSUE THREAD

**Issue by naufaldi** [naufaldi/nextjs-chakra-notion-blog#3]
Setup Struktur Folder dan Layout agar sesuai dengan project yang akan datang. 
- Layout 
- Component
- Pages untuk Blog

Contoh Layout bisa dilihat di [Landing VPN](https://github.com/naufaldi/next-landing-vpn/tree/main/components) atau memiliki saran struktur folder lain bisa memberikan komentar

**Comment by Aqshola** [comment]
wip

**Comment by naufaldi** [comment]
done
